http:
  port: 3037
  enable: yes
email:
  default_domain: "lists.fsbbs.org"
  theme_plain: default_mail_plain
  subject_format: "[fsbbs] - {}"
  outgoing:
    provider: txSendmail
    host: localhost
  incoming:
    enable: yes
    port: 2500
redis:
  host: 127.0.0.1
  port: 6379
  pool_size: 2
notify:
  im:
    servers:
      - hostname: "irc.freenode.net"
        realname: "fsbbs bot"
        nickname: "fsbbs"
        port: 6667
        channels: ["#fseek"]
        type: irc
        